# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 034e1a868b6b1f999896112ee0f24009a271385684aec465205d23f920f6e4e3e0694a480f827ebd4f123012804338f35ddd07f2e3d5912c62b318724323dde6

test:
  secret_key_base: 924bcedb925a2bc91322d99836e4e0908f1573921556c48075708a83aac3087b28e7b69d2a965320ab86286db79d7dbea41275cdf93e39d696e488d9b9f0d8b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
